name = "ARGr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ea4f281d6c13527c37fbd2e775555a2f2bf65408942b12c38b7b00cdf5680f1"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
